config/routes.rb
Rails.application.routes.draw do
  get "users/new"
  get 'user/new'
  # get 'static_pages/home'
  root "static_pages#home", as: 'default'
  get 'home',     to: 'static_pages#home'
  get 'help',     to: 'static_pages#help', as: 'help'
  get 'about',    to: 'static_pages#about'
  get 'contact',  to: 'static_pages#contact'
  get 'signup',   to: 'users#new'

  resources :users

  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "static_pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # same as before_save { self.email = email.downcase }
  before_save { email.downcase! }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates(:name, presence: true, length: { maximum: 50 })
  validates :email,
            presence:   true,
            length:     { maximum: 255 },
            format:     { with: VALID_EMAIL_REGEX },
            uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  # returns the hash digest of the given string
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    # This is what I created on my own without the book

    # @user = User.find_by(email: params[:session][:email])
    # if @user != nil
    #   if @user.authenticate(params[:session][:password])
    #     flash[:success] = "Welcome #{@user.name}!"
    #     redirect_to @user
    #   else
    #     flash[:danger] = "Wrong password"
    #     render 'new'
    #   end
    # else
    #   flash[:danger] = "No user associated with that email"
    #   render 'new'
    # end

    # This is the solution from the book:
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      # The above line is the same as user && user.authenticate(params[:session][:password])
      reset_session
      log_in user # redirects based on the class for user
      redirect_to user
      flash.now[:success] = "Welcome, #{user.name}"
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to home_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params) # Not the final implementation
    if @user&.save
      reset_session
      log_in @user
      flash[:success] = 'Welcome to the Sample App!'
      # This is the same as redirect_to user_url(@user)
      # Rails automatically redirects to user_url
      # based on the class of the object pass to the redirect_to function
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

 #Returns the full title on a per page basis
 def full_title(page_title='')
  base_title = "Ruby on Rails Tutorial Sample App"
  if page_title.empty?
   base_title
  else
   "#{page_title} | #{base_title}"
  end
 end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    reset_session
    @current_user = nil
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="https://www.michaelhartle.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%=link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="https://news.railstutorial.org">News</a> </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", '#', id: "logo" %>
    <nav>
      <div class="navbar-header">
        <button id="hamburger" type="button" class="navbar-toggle collapsed">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar>"></span>
          <span class="icon-bar>"></span>
          <span class="icon-bar>"></span>
          <a class="navbar-brand" href="#">X</a>
        </button>
      </div>
      <ul id="navbar-menu"
        class="nav navbar-nav navbar-right collapse navbar-collapse">
        <li><%= link_to "Home", default_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" id="account" class="dropdown-toggle">
              Account <b class="caret"></b>
            </a>
            <ul id="dropdown-menu" class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path,
                            data: { "turbo-method": :delete } %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!-- [if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= render 'layouts/shim' %>
    <%= hotwire_livereload_tags if Rails.env.development? %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params.to_yaml) if Rails.env.development? %>
  </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <body>
    <h1>About page</h1>
    <p>
      Get help on teh Ruby on Rails Tutorial at the
      <a href="https://www.railstutorial.org/help">Rails Tutorial Help Page</a>
    </p>
  </body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<!DOCTYPE html>

<html>
  <body>
    <h1><%= yield(:title) %> page</h1>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
  <body>
    <h1>Help</h1>
    <p>
      Get help on teh Ruby on Rails Tutorial at the
      <a href="https://www.railstutorial.org/help">Rails Tutorial Help Page</a>
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>

    <h2>
      This is the home page for the
      <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application
    </h2>
    <%=link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <%#=link_to "Log in", login_path, class: 'btn btn-lg btn-primary' %>
  </div>
<%=link_to image_tag("rails.svg", alt: "Rails logo", width: "200"), "https://rubyonrails.org/" %>
<%#= image_tag("cat.png", alt: "Picture of cat", width: "200") %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1><%= yield(:title) %></h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.text_field :password,  class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.text_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my Account", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--<body>-->
<!--  <%#= @user.name %>, <%#= @user.email %>, <%#= @user.created_at %>-->
<!--  <br>-->
<!--  <br>-->
  <%#= Time.now %>
<!--</body>-->

<% provide(:title, @user.name) %>


<div class="row">
  <aside class="col-md-4">
    <h1>
      <%= gravatar_for @user %>
      <%= @user.name %>
    </h1>
  </aside>
</div>